def Display():
    print("Programming language:")
    print("Bio-python")
    print("java")
    print("SQL")
    print("c")
    print("c++")
Display()
Display()
Display()
Display()
Display()
Display()
Display()