st=[]*4   #Data structure size
st.append(10)
st.append(20)
st.append(30)
st.append(40)
print(st)
st.pop()
print(st)
st.pop()
print(st)
st.pop()
print(st)
st.pop()
print(st)

from collections import deque
st=deque(maxlen=4)
st.append(10)
st.append(20)
st.append(30)
st.append(40)
print(st)
st.pop()
print(st)
st.pop()
print(st)
st.pop()
print(st)
st.pop()

from queue import LifoQueue
stack=LifoQueue(maxsize=3)
print(stack.qsize())
stack.put('a')
stack.put('b')
stack.put('c')
print("Full:",stack.full())
print("Size:",stack.qsize())
print('\nElements popped form stack')
print(stack.get())
print(stack.get())
print(stack.get())