a=int(input("enter int value:"))
print("int value before conversion:",a)
print("int value after converting into float:",float(a))
print("int value after converting into string:",str(a))
print("int value after converting into complex:",complex(a))
print()
b=float(input("enter a float value:"))
print("float value before conversion:",b)
print("float value after converting into integer:",int(b))
print("float value after converting into string:",str(b))
print("float value after converting into complex:",complex(b))
print()
c=str(input("enter a string value:"))
print("string value before conversion:",c)
print("string value after converting into integer:",int(c))
print("string value after converting into float:",float(c))
print("string value after converting into list:",list(c))
print("string value after converting into tuple:",tuple(c))