#Tuple Packing
Prog_Lang='C','Python','NOSQL','Java','HTML','CSS','AngularJS','R','ReactJS','NodeJS','SQL','MAngodb','Cython','Zython','Rubypython'
print(Prog_Lang)
print(type(Prog_Lang))
#Tuple Unpacking
#acessing using indexing
print("Acessing list elements using +ve indexing")
print(Prog_Lang[0])
print(Prog_Lang[1])
print(Prog_Lang[2])
print(Prog_Lang[3])
print(Prog_Lang[4])
print(Prog_Lang[5])
print(Prog_Lang[6])
print(Prog_Lang[7])
print(Prog_Lang[8])
print(Prog_Lang[9])
print(Prog_Lang[10])
print(Prog_Lang[11])
print(Prog_Lang[12])
print(Prog_Lang[13])
print(Prog_Lang[14])
#acessing using negative indexing
print("Acessing using -ve indexing")
print(Prog_Lang[-15])
print(Prog_Lang[-14])
print(Prog_Lang[-13])
print(Prog_Lang[-12])
print(Prog_Lang[-11])
print(Prog_Lang[-10])
print(Prog_Lang[-9])
print(Prog_Lang[-8])
print(Prog_Lang[-7])
print(Prog_Lang[-6])
print(Prog_Lang[-5])
print(Prog_Lang[-4])
print(Prog_Lang[-3])
print(Prog_Lang[-2])
print(Prog_Lang[-1])